packages:
  - packages/*

onlyBuiltDependencies:
  - classic-level
  - esbuild
  - msgpackr-extract
  - tree-sitter
  - tree-sitter-bash
  - tree-sitter-css
  - tree-sitter-html
  - tree-sitter-javascript
  - tree-sitter-jsdoc
  - tree-sitter-json
  - tree-sitter-typescript
