packages:
  - apps/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - classic-level
  - esbuild
  - msgpackr-extract
  - tree-sitter
  - tree-sitter-bash
  - tree-sitter-c
  - tree-sitter-c-sharp
  - tree-sitter-cpp
  - tree-sitter-css
  - tree-sitter-go
  - tree-sitter-html
  - tree-sitter-javascript
  - tree-sitter-jsdoc
  - tree-sitter-json
  - tree-sitter-python
  - tree-sitter-typescript
