import type { ShortcutsMap } from './app-settings';

export const defaultShortcuts: ShortcutsMap = {
  'file.new': 'CmdOrCtrl+N',
  'file.open': 'CmdOrCtrl+O',
  'file.save': 'CmdOrCtrl+S',
  'file.saveAs': 'CmdOrCtrlCtrl+Shift+S',
  'file.close': 'CmdOrCtrl+W',
  'file.export': 'CmdOrCtrl+E',
  'edit.undo': 'CmdOrCtrl+Z',
  'edit.redo': 'CmdOrCtrl+Y',
  'edit.cut': 'CmdOrCtrl+X',
  'edit.copy': 'CmdOrCtrl+C',
  'edit.paste': 'CmdOrCtrl+V',
  'edit.selectAll': 'CmdOrCtrl+A',
  'edit.find': 'CmdOrCtrl+F',
  'edit.replace': 'CmdOrCtrl+H',
  'view.zoomIn': 'CmdOrCtrl+=',
  'view.zoomOut': 'CmdOrCtrl+-',
  'view.resetZoom': 'CmdOrCtrl+0',
  'view.toggleSidebar': 'CmdOrCtrl+B',
  'view.fullScreen': 'F11',
  'navigate.back': 'Alt+Left',
  'navigate.forward': 'Alt+Right',
  'navigate.home': 'Alt+Home',
  'note.createRichText': 'CmdOrCtrl+Shift+N',
  'note.createMarkdown': 'CmdOrCtrl+Alt+M',
  'note.createCode': 'CmdOrCtrl+Alt+C',
  'note.createTable': 'CmdOrCtrl+Alt+T',
  'note.createMindMap': 'CmdOrCtrl+Alt+G',
  'note.createFlowchart': 'CmdOrCtrl+Alt+F',
  'search.quickOpen': 'CmdOrCtrl+P',
  'search.globalSearch': 'CmdOrCtrl+Shift+P',
  'search.searchInFiles': 'CmdOrCtrl+Shift+F',
  'workspace.switch': 'CmdOrCtrl+K',
  'workspace.create': 'CmdOrCtrl+Shift+K',
  'app.settings': 'CmdOrCtrl+,',
  'app.quit': 'CmdOrCtrl+Q',
  'app.reload': 'CmdOrCtrl+R',
  'ai.quickChat': 'CmdOrCtrl+I',
  'ai.analyzeCode': 'CmdOrCtrl+Shift+I',
  'help.documentation': 'F1',
  'help.shortcuts': 'CmdOrCtrl+/'
};
